version: "3.1"

services:
  php:
    build: .
    # image: php:7.4-apache
    ports:
      - 80:80
    volumes:
      - ../:/var/www/html/
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ../logs:/usr/src/fileserver/docker/logs
      - ./apache/site-default.conf:/etc/apache2/sites-enabled/000-default.conf
    environment:
      - XDEBUG_SESSION=1
